# Secret Scanning configuration for GHAS validation
# This file allows specific secrets to be permitted for validation purposes

version: 1

patterns:
  # Stripe Test API Secret Key (ダミー検証用)
  - pattern: 'sk_test_4eC39HqLyjWDarhtT657G78z'
    comment: 'Dummy Stripe test key for GHAS validation'
    type: 'stripeApiKey'

  # Slack API Token (ダミー検証用)
  - pattern: 'xoxb-123456789012-1234567890123-AbCdEfGhIjKlMnOpQrStUv'
    comment: 'Dummy Slack bot token for GHAS validation'
    type: 'slackBotToken'
